### ISSUE TITLE
Create Config Config (Thingy???? )

### ISSUE THREAD

**Issue by wolflord212312** [JustRed23/ABCM#3]
So basicly you would type
```
//make a config save location so you can save it to a directory/have it make a directory to store the configs if you are making more then one, so if you did Config.savelocation(configs\UwU\(configfilename)
config.savelocation()
Config.create(),
//So it would be like nerd.cfg if you add a name otherwise errors out or make random name.
Config.name(NERD)
//Could be done with annotations
//(name of field),Type,content of field,description or whatever after)
Config.add((wahterver),String,"WHATEVER BLABLAH")
Config.add((number),Int,1)
```

**Comment by wolflord212312** [comment]
Oh you would also need a way to load that config file so instead of loading by class add a way to laod cfg files?

**Comment by JustRed23** [comment]
ABCM is made specifically for housing config files in one directory, you can change the directory by using `Config.setConfigDir`.
Also, setting config values manually was not my intention, you can just make a class, set the fields there to a different value and call `Config.save`
