### ISSUE TITLE
Could not use param ''?

### ISSUE THREAD

**Issue by wolflord212312** [JustRed23/ABCM#4]
Config class
import dev.JustRed23.abcm.ConfigField;
import dev.JustRed23.abcm.Configurable;

@Configurable
public class BotConfig {
    @ConfigField(defaultValue = "true")
    public static boolean enabled;

    @ConfigField(defaultValue = "BotToken")
    public static String token;

    @ConfigField(defaultValue = "Foxy")
    public static String name;

    @ConfigField(defaultValue = "Knox-TestBot",description = "Is the Status default is Watching Minecraft")
    public static String Watching;
    @ConfigField(defaultValue = "hub.reforgednetwork.com",description = "The Minecraft Server Ip")
    public static String IP;
}

Main

public static void main(String[] args) {
        Config.addScannable(BotConfig.class);
        Config.setDebug(true);
        try {
            Config.init();
        } catch (ConfigInitException e) {
            throw new RuntimeException(e);
        }
        LOGGER = Logger.getLogger(BotConfig.name);
        if (!BotConfig.enabled) {
            LOGGER.log(Level.INFO, "Bot is disabled, make sure all the values in magma.cfg are set!");
            BotCommons.shutdown(instance);
            return;
        }
        builder = JDABuilder.createDefault(BotConfig.token)
                .setBulkDeleteSplittingEnabled(false)
                .setEnableShutdownHook(false)
                .setEnabledIntents(
                        GatewayIntent.DIRECT_MESSAGES,
                        GatewayIntent.GUILD_MESSAGES,
                        GatewayIntent.GUILD_MESSAGE_REACTIONS,
                        GatewayIntent.GUILD_MEMBERS,
                        GatewayIntent.MESSAGE_CONTENT
                )
                .disableCache(
                        CacheFlag.ACTIVITY,
                        CacheFlag.VOICE_STATE,
                        CacheFlag.SCHEDULED_EVENTS,
                        CacheFlag.EMOJI,
                        CacheFlag.STICKER
                )
                .setChunkingFilter(ChunkingFilter.ALL)
                .setMemberCachePolicy(MemberCachePolicy.ALL)
                .setStatus(getStatus())
                .setActivity(getActivity());
        instance = builder.build();
        try {
            getInstance().awaitReady();
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }

        // Minecraft server status checking code
        String serverAddress = BotConfig.IP; // replace with your server address
        ServerStatusChecker checker = new ServerStatusChecker(serverAddress);
        checker.startChecking();

        // Example usage:
        while (true) {
            System.out.println("Server is " + (checker.isOnline() ? "online" : "offline"));
            System.out.println("Online players: " + checker.getOnlinePlayers());
            System.out.println("Max players: " + checker.getMaxPlayers());
            try {
                Thread.sleep(5000);
            } catch (InterruptedException e) {
                System.out.println("Interrupted while sleeping: " + e.getMessage());
                return;
            }
        }
    }

**Comment by JustRed23** [comment]
Can you give an explanation as to what isnt working?

**Comment by JustRed23** [comment]
Fixed in version 1.9
